### ISSUE TITLE
Todo before stable release

### ISSUE THREAD

**Issue by k-ode** [ConrabOpto/mst-query#10]
- [X] Change the return type of result in next to `any`.
- [X] Add `updatedAt`
- [X] Move queryCache to QueryClient class, expose on environment
- [X] Put env, rootStore, queryCache on Provider and expose via hooks

**Comment by k-ode** [comment]
Will release a first major version when we merge #11 .
